name: Run Selenium Tests on macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  selenium-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

     # - name: Install dependencies
     #   run: |
     #     python -m pip install --upgrade pip
     #     pip install -r requirements.txt
#
     # - name: Mostrar versión Python y paquetes
     #   run: |
     #     python --version
     #     pip show selenium
     #     pip show webdriver-manager
     #     pip show pytest
#
     # - name: Listar archivos en directorio
     #   run: ls -lR
#
     # - name: Instalar Google Chrome en macOS (si es necesario)
     #   run: |
#
     #     brew install --cask google-chrome || echo "Chrome ya instalado"
     # - name: Debug - Chrome version
     #   run: google-chrome --version || echo "Chrome no encontrado"
#
     # - name: List files for debug
     #   run: ls -lR
#
     # - name: Run tests with verbose and show all output
     #   run: pytest tests/ -v --maxfail=5 --capture=no
#

